# Common base Compose file for dev/test/prod environments:
version: "3.7"
networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  database:
    image: postgres:12.4
    environment:
      POSTGRES_DB: agent_test 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
    ports:
      - "5432:5432"

  agent-api:
    image: agent-api:tag
    environment:
      spring.datasource.url: jdbc:postgresql://database/agent_test?currentSchema=agent
      spring.datasource.username: postgres
      spring.datasource.password: p
      spring.datasource.continue-on-error: "true"
      spring.liquibase.user: postgres
      spring.liquibase.password: p
    labels:
      - "traefik.http.routers.objectstore-api.rule=Host(`${DINAUI_DOMAIN}`)"
    ports:
      - "80:8080"
        
  traefik:
    image: traefik:v2.2.0
    command: --providers.docker=true
    ports:
      - "80" # Traefik-connected services
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock



