# Common base Compose file for dev/test/prod environments:
version: "3.7"
networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  database:
    image: postgres:12.4
    environment:
      POSTGRES_DB: agent_test 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
    ports:
      - "5432:5432"




