version: "3.7"
networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: seqdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
  seqdb-api:
    image: seqdb-api:tag
    environment:
      spring.datasource.url: jdbc:postgresql://database/seqdb?currentSchema=seqdb
      spring.datasource.username: postgres
      spring.datasource.password: p
      spring.datasource.continue-on-error: "true"
      spring.liquibase.user: postgres
      spring.liquibase.password: p
